#!/usr/bin/env python
import clustohttp
import jinja2

import optparse
import logging
import difflib
import socket
import sys


def serversort(servers):
    servers.sort(key=lambda x: (x.datacenter, x.name))
    return servers


def main():
    parser = optparse.OptionParser(
        usage='%prog [options] <template> <output file>')
    parser.add_option('-r', '--root', dest='template_root',
        default='/usr/share/python-clustoclient/templates',
        help='Absolute path to template directory')
    parser.add_option('-n', '--name', dest='name',
        default=socket.gethostname().split('.', 1)[0],
        help='Name of the clusto object to query attributes from. Default ' +
             'is this system\'s hostname without a domain part')
    parser.add_option('-v', '--verbose', dest='verbose', action='store_true',
        help='Writes status messages and a diff to stderr if the output ' +
             'file differs from the existing file on disk')
    options, args = parser.parse_args()

    if len(args) < 2:
        parser.print_help()
        return -1
    template, outputfile = args[:2]

    tenv = jinja2.Environment(trim_blocks=True,
        loader=jinja2.FileSystemLoader(options.template_root))
    tenv.filters['serversort'] = serversort

    clusto = clustohttp.ClustoProxy()

    try:
        server = clusto.get_by_name(options.name)
    except LookupError, e:
        sys.stderr.write(str(e) + '\n')
        return -1

    try:
        template = tenv.get_template(template)
    except jinja2.TemplateNotFound, e:
        sys.stderr.write('Unable to find template: %s/%s\n' % (options.template_root, template))
        sys.stderr.write(str(e) + '\n')
        return -1

    output = template.render(server=server, clusto=clusto)

    if outputfile != '-':
        try:
            existing = file(outputfile, 'r').read()
            if existing == output:
                if options.verbose:
                    log.critical('Rendered template matches output file, not overwriting.')
                return 0
        except Exception, e:
            log.exception('Unable to read target file, assuming empty')
            existing = ''

        if options.verbose:
            diff = difflib.context_diff([existing], [output], lineterm='\n')
            for line in diff:
                sys.stderr.write(line)
            sys.stderr.write('\n')
            sys.stderr.flush()
        fd = file(outputfile, 'w')
    else:
        fd = sys.stdout
    fd.write(output)
    fd.flush()
    fd.close()
    return 0


if __name__ == '__main__':
    sys.exit(main())
